# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
zh:
  languageCode: zh-Hans
  contentDir: content/zh
  title: 朱子恒
  params:
    description: 朱子恒，清华大学博士研究生，研究方向包括电力系统规划、可再生能源并网、电力市场与人工智能赋能的能源系统分析。
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
